# Generated by Django 5.0.7 on 2024-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('member_phone', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('member_profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('member_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
