create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50),
	model VARCHAR(50),
	price VARCHAR(50)
);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$35927.30');
insert into car (make, model, price) values ('Dodge', 'Viper', '$57001.92');
insert into car (make, model, price) values ('Volkswagen', 'Touareg', '$33496.48');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$79625.25');
insert into car (make, model, price) values ('Infiniti', 'G', '$79027.61');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '$43480.15');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$64232.00');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '$75965.72');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '$99795.96');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$23454.81');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '$78709.86');
insert into car (make, model, price) values ('Aston Martin', 'Vantage', '$16664.69');
insert into car (make, model, price) values ('Ford', 'LTD', '$50844.66');
insert into car (make, model, price) values ('Audi', 'Coupe GT', '$17093.30');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '$18182.18');
insert into car (make, model, price) values ('Honda', 'Accord', '$69780.41');
insert into car (make, model, price) values ('Buick', 'LeSabre', '$21676.78');
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', '$70244.08');
insert into car (make, model, price) values ('Suzuki', 'SJ', '$90090.28');
insert into car (make, model, price) values ('Bentley', 'Continental', '$10968.71');
insert into car (make, model, price) values ('BMW', '7 Series', '$23983.49');
insert into car (make, model, price) values ('Kia', 'Optima', '$70046.10');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$46928.67');
insert into car (make, model, price) values ('Porsche', 'Panamera', '$36975.99');
insert into car (make, model, price) values ('Subaru', 'Baja', '$72719.54');
insert into car (make, model, price) values ('Volkswagen', 'rio', '$27218.23');
insert into car (make, model, price) values ('Honda', 'S2000', '$44085.10');
insert into car (make, model, price) values ('Audi', '80', '$73959.10');
insert into car (make, model, price) values ('Audi', 'A8', '$87650.99');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$75817.69');
insert into car (make, model, price) values ('Mazda', 'MPV', '$17114.83');
insert into car (make, model, price) values ('Nissan', 'Versa', '$62357.90');
insert into car (make, model, price) values ('Land Rover', 'Sterling', '$45192.60');
insert into car (make, model, price) values ('Toyota', 'Celica', '$19353.12');
insert into car (make, model, price) values ('Maybach', '62', '$92141.57');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$20322.32');
insert into car (make, model, price) values ('Infiniti', 'G', '$27086.52');
insert into car (make, model, price) values ('Dodge', 'Durango', '$16918.30');
insert into car (make, model, price) values ('Ford', 'F-Series', '$66602.37');
insert into car (make, model, price) values ('BMW', '760', '$54982.11');
insert into car (make, model, price) values ('Mercury', 'Mariner', '$72739.63');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '$26859.36');
insert into car (make, model, price) values ('Volvo', 'XC70', '$14348.08');
insert into car (make, model, price) values ('Mitsubishi', 'GTO', '$57527.35');
insert into car (make, model, price) values ('Toyota', 'Paseo', '$64423.75');
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', '$56260.31');
insert into car (make, model, price) values ('GMC', 'Suburban 2500', '$97311.51');
insert into car (make, model, price) values ('Ford', 'Freestar', '$51425.49');
insert into car (make, model, price) values ('Kia', 'Sportage', '$10492.11');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$70378.10');
insert into car (make, model, price) values ('Ford', 'Edge', '$52466.50');
insert into car (make, model, price) values ('Jaguar', 'XK', '$44899.74');
insert into car (make, model, price) values ('Subaru', 'Forester', '$69355.81');
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', '$64144.34');
insert into car (make, model, price) values ('Audi', 'Q7', '$81755.64');
insert into car (make, model, price) values ('Chevrolet', 'Cruze', '$40013.74');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$80665.26');
insert into car (make, model, price) values ('Volvo', 'V70', '$72363.78');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$99969.47');
insert into car (make, model, price) values ('Ford', 'Edge', '$42974.67');
insert into car (make, model, price) values ('Audi', 'A8', '$45872.47');
insert into car (make, model, price) values ('Mazda', 'MX-5', '$65850.03');
insert into car (make, model, price) values ('Toyota', '4Runner', '$65524.61');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '$70030.54');
insert into car (make, model, price) values ('Mazda', 'Mazda3', '$52979.68');
insert into car (make, model, price) values ('Ford', 'Taurus', '$15604.25');
insert into car (make, model, price) values ('Ford', 'Courier', '$60446.70');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$12821.52');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '$37533.89');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '$24417.29');
insert into car (make, model, price) values ('Lincoln', 'MKT', '$57416.19');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$15921.43');
insert into car (make, model, price) values ('Ford', 'Taurus', '$62119.68');
insert into car (make, model, price) values ('Lexus', 'GS', '$86686.43');
insert into car (make, model, price) values ('Porsche', '911', '$60215.27');
insert into car (make, model, price) values ('Kia', 'Sedona', '$67241.05');
insert into car (make, model, price) values ('Audi', 'S4', '$98691.64');
insert into car (make, model, price) values ('Porsche', 'Boxster', '$27445.64');
insert into car (make, model, price) values ('Fiat', 'Nuova 500', '$17875.82');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$74246.86');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '$12442.32');
insert into car (make, model, price) values ('Toyota', 'Previa', '$84376.31');
insert into car (make, model, price) values ('Lexus', 'ES', '$68156.19');
insert into car (make, model, price) values ('Mercury', 'Tracer', '$20253.19');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '$93863.35');
insert into car (make, model, price) values ('Audi', 'A4', '$97851.72');
insert into car (make, model, price) values ('GMC', 'Sierra', '$80676.42');
insert into car (make, model, price) values ('Mazda', 'Familia', '$40532.57');
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', '$94037.01');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$34651.68');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$40958.77');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '$95518.99');
insert into car (make, model, price) values ('Plymouth', 'Horizon', '$65042.42');
insert into car (make, model, price) values ('Hummer', 'H3', '$91543.12');
insert into car (make, model, price) values ('Acura', 'NSX', '$78086.71');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '$63122.52');
insert into car (make, model, price) values ('Dodge', 'Charger', '$76808.10');
insert into car (make, model, price) values ('Ford', 'Probe', '$55302.89');
insert into car (make, model, price) values ('Infiniti', 'G', '$38297.88');
insert into car (make, model, price) values ('Honda', 'S2000', '$15798.65');
insert into car (make, model, price) values ('Jeep', 'Commander', '$29435.48');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '$42997.26');
insert into car (make, model, price) values ('Kia', 'Spectra', '$38198.84');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '$84490.98');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '$96499.17');
insert into car (make, model, price) values ('Toyota', 'Corolla', '$73073.20');
insert into car (make, model, price) values ('GMC', 'Vandura G3500', '$62726.09');
insert into car (make, model, price) values ('Acura', 'RL', '$92406.56');
insert into car (make, model, price) values ('Ford', 'Tempo', '$74838.16');
insert into car (make, model, price) values ('Honda', 'S2000', '$28602.00');
insert into car (make, model, price) values ('Lexus', 'IS-F', '$97972.29');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$30433.96');
insert into car (make, model, price) values ('Saab', '9-3', '$52048.45');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '$75431.05');
insert into car (make, model, price) values ('Buick', 'LeSabre', '$36596.93');
insert into car (make, model, price) values ('Honda', 'Pilot', '$88461.61');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$18781.70');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '$90733.16');
insert into car (make, model, price) values ('Subaru', 'Outback', '$39616.27');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '$28261.12');
insert into car (make, model, price) values ('Toyota', 'Paseo', '$60381.24');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '$68820.12');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '$65188.41');
insert into car (make, model, price) values ('Studebaker', 'Avanti', '$80337.40');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '$70600.29');
insert into car (make, model, price) values ('GMC', 'Safari', '$45702.72');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$74293.85');
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', '$90039.65');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$28417.35');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$17880.05');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '$62462.15');
insert into car (make, model, price) values ('Lotus', 'Esprit Turbo', '$58287.42');
insert into car (make, model, price) values ('Kia', 'Spectra', '$14080.55');
insert into car (make, model, price) values ('Nissan', 'Altima', '$42504.36');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '$21842.83');
insert into car (make, model, price) values ('Ford', 'Taurus', '$43785.74');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$31804.64');
insert into car (make, model, price) values ('Toyota', 'Previa', '$99607.35');
insert into car (make, model, price) values ('Dodge', 'Neon', '$66088.42');
insert into car (make, model, price) values ('Dodge', 'Dynasty', '$33668.35');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$73586.20');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '$45626.73');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '$85537.30');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '$77104.63');
insert into car (make, model, price) values ('Toyota', 'Tercel', '$10269.42');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '$32204.26');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '$84913.06');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '$28061.45');
insert into car (make, model, price) values ('Honda', 'S2000', '$29566.03');
insert into car (make, model, price) values ('Porsche', '944', '$86025.32');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$60066.90');
insert into car (make, model, price) values ('Infiniti', 'QX', '$16465.21');
insert into car (make, model, price) values ('GMC', 'Sonoma', '$86803.88');
insert into car (make, model, price) values ('Toyota', 'Supra', '$37471.76');
insert into car (make, model, price) values ('Buick', 'Skylark', '$45406.18');
insert into car (make, model, price) values ('Mercury', 'Mystique', '$76252.74');
insert into car (make, model, price) values ('Dodge', 'Stratus', '$64227.36');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$72130.81');
insert into car (make, model, price) values ('Ford', 'F150', '$60014.61');
insert into car (make, model, price) values ('Kia', 'Spectra', '$46491.62');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '$17301.31');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$62029.21');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '$85213.03');
insert into car (make, model, price) values ('Geo', 'Tracker', '$14504.07');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '$50245.06');
insert into car (make, model, price) values ('Ford', 'Contour', '$41781.04');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', '$95547.09');
insert into car (make, model, price) values ('Buick', 'Coachbuilder', '$18297.78');
insert into car (make, model, price) values ('Mazda', 'CX-9', '$29814.83');
insert into car (make, model, price) values ('Acura', 'RSX', '$63908.76');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '$66557.80');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '$85775.83');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$54465.21');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '$68341.55');
insert into car (make, model, price) values ('Ford', 'Edge', '$67785.88');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '$13941.82');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '$66030.91');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$17934.15');
insert into car (make, model, price) values ('Pontiac', 'Aztek', '$58325.59');
insert into car (make, model, price) values ('Suzuki', 'Kizashi', '$79129.85');
insert into car (make, model, price) values ('Subaru', 'Brat', '$68611.37');
insert into car (make, model, price) values ('Ford', 'F-Series', '$16590.08');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '$99356.63');
insert into car (make, model, price) values ('Mazda', 'Protege', '$24500.60');
insert into car (make, model, price) values ('Dodge', 'Viper', '$65218.24');
insert into car (make, model, price) values ('Pontiac', '6000', '$84181.72');
insert into car (make, model, price) values ('GMC', 'Yukon', '$26492.56');
insert into car (make, model, price) values ('Chevrolet', '2500', '$69515.35');
insert into car (make, model, price) values ('Ford', 'Explorer', '$88121.62');
insert into car (make, model, price) values ('Cadillac', 'Brougham', '$44014.58');
insert into car (make, model, price) values ('Chevrolet', '1500', '$21318.06');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '$47902.81');
insert into car (make, model, price) values ('Ford', 'Escort', '$77396.69');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '$10550.34');
insert into car (make, model, price) values ('Mercury', 'Sable', '$34403.99');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$54388.03');
insert into car (make, model, price) values ('GMC', 'Envoy', '$34163.59');
insert into car (make, model, price) values ('BMW', 'M5', '$55887.24');
insert into car (make, model, price) values ('BMW', 'X3', '$39434.22');
insert into car (make, model, price) values ('Ford', 'GT500', '$28558.09');
insert into car (make, model, price) values ('Lexus', 'RX', '$72476.48');
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', '$19144.37');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '$54819.05');
insert into car (make, model, price) values ('Acura', 'Integra', '$13742.47');
insert into car (make, model, price) values ('Chrysler', 'Voyager', '$69193.72');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '$37618.86');
insert into car (make, model, price) values ('Ford', 'Aspire', '$27494.04');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$71120.57');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$50101.16');
insert into car (make, model, price) values ('Aston Martin', 'DB9 Volante', '$41939.41');
insert into car (make, model, price) values ('Dodge', 'Journey', '$65537.19');
insert into car (make, model, price) values ('Honda', 'Accord', '$11355.85');
insert into car (make, model, price) values ('Hyundai', 'Scoupe', '$76038.56');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$52460.40');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$17473.45');
insert into car (make, model, price) values ('BMW', 'M5', '$76782.85');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$83754.60');
insert into car (make, model, price) values ('Dodge', 'Avenger', '$61526.65');
insert into car (make, model, price) values ('Dodge', 'Ram 1500 Club', '$59404.56');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$16268.28');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$66837.68');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '$72198.75');
insert into car (make, model, price) values ('Volkswagen', 'Routan', '$76385.84');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$40330.46');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$76126.74');
insert into car (make, model, price) values ('Mazda', 'Familia', '$93528.01');
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', '$65198.28');
insert into car (make, model, price) values ('Ford', 'Mustang', '$88481.53');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '$54922.31');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '$67487.04');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$80662.15');
insert into car (make, model, price) values ('BMW', '3 Series', '$22870.97');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '$28068.88');
insert into car (make, model, price) values ('BMW', '8 Series', '$46705.77');
insert into car (make, model, price) values ('Porsche', 'Cayman', '$26617.97');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$57815.94');
insert into car (make, model, price) values ('Toyota', 'Celica', '$82292.78');
insert into car (make, model, price) values ('Volkswagen', 'Type 2', '$71521.12');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$85424.81');
insert into car (make, model, price) values ('Cadillac', 'Allante', '$45814.01');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$27914.34');
insert into car (make, model, price) values ('Honda', 'Element', '$90061.28');
insert into car (make, model, price) values ('Dodge', 'Viper RT/10', '$34583.49');
insert into car (make, model, price) values ('Ford', 'Galaxie', '$42157.88');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$45518.33');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$96971.57');
insert into car (make, model, price) values ('Honda', 'Civic', '$33052.87');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$77529.30');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '$37127.75');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '$33216.54');
insert into car (make, model, price) values ('BMW', '650', '$12520.91');
insert into car (make, model, price) values ('Pontiac', 'Gemini', '$41827.42');
insert into car (make, model, price) values ('Pontiac', 'GTO', '$46256.25');
insert into car (make, model, price) values ('Acura', 'Vigor', '$96097.03');
insert into car (make, model, price) values ('Audi', 'S6', '$86152.96');
insert into car (make, model, price) values ('Mazda', '929', '$55363.60');
insert into car (make, model, price) values ('Toyota', 'Supra', '$58800.71');
insert into car (make, model, price) values ('Maybach', '57', '$20623.66');
insert into car (make, model, price) values ('Dodge', 'Stratus', '$60180.77');
insert into car (make, model, price) values ('Audi', 'A8', '$69208.28');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$28639.23');
insert into car (make, model, price) values ('Hyundai', 'Tucson', '$29911.34');
insert into car (make, model, price) values ('Cadillac', 'CTS', '$16123.98');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$97484.02');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '$62723.37');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '$93972.51');
insert into car (make, model, price) values ('Volkswagen', 'CC', '$69758.34');
insert into car (make, model, price) values ('Kia', 'Sephia', '$32321.33');
insert into car (make, model, price) values ('BMW', 'X6 M', '$10153.13');
insert into car (make, model, price) values ('Tesla', 'Roadster', '$65477.60');
insert into car (make, model, price) values ('Buick', 'Century', '$35629.26');
insert into car (make, model, price) values ('Toyota', 'Previa', '$15455.58');
insert into car (make, model, price) values ('Audi', 'A6', '$97508.62');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$76543.61');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$79735.04');
insert into car (make, model, price) values ('Mazda', 'MPV', '$34194.24');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '$47438.66');
insert into car (make, model, price) values ('Ford', 'F150', '$44310.26');
insert into car (make, model, price) values ('Ford', 'Taurus', '$62507.85');
insert into car (make, model, price) values ('Subaru', 'Impreza WRX', '$38523.08');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '$95385.13');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '$55834.68');
insert into car (make, model, price) values ('Dodge', 'Ram', '$78705.15');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '$71556.32');
insert into car (make, model, price) values ('Eagle', 'Talon', '$17934.31');
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', '$49720.89');
insert into car (make, model, price) values ('BMW', '530', '$62523.22');
insert into car (make, model, price) values ('Kia', 'Rio', '$63490.48');
insert into car (make, model, price) values ('Ford', 'Expedition', '$48139.05');
insert into car (make, model, price) values ('Buick', 'Skyhawk', '$70099.06');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$36363.10');
insert into car (make, model, price) values ('MINI', 'Countryman', '$49075.38');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '$14765.42');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '$65454.94');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '$19256.38');
insert into car (make, model, price) values ('Ford', 'Falcon', '$98615.07');
insert into car (make, model, price) values ('Ford', 'Taurus', '$83513.65');
insert into car (make, model, price) values ('Honda', 'Element', '$54191.97');
insert into car (make, model, price) values ('Toyota', 'Celica', '$97990.50');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$16268.08');
insert into car (make, model, price) values ('Dodge', 'Ramcharger', '$99452.15');
insert into car (make, model, price) values ('Buick', 'Century', '$52758.83');
insert into car (make, model, price) values ('Toyota', 'RAV4', '$99452.46');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$16082.05');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '$62826.58');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '$49676.07');
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', '$10330.03');
insert into car (make, model, price) values ('Hyundai', 'Scoupe', '$97818.07');
insert into car (make, model, price) values ('Chrysler', '300', '$44501.19');
insert into car (make, model, price) values ('Suzuki', 'Forenza', '$22194.70');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$35648.02');
insert into car (make, model, price) values ('Isuzu', 'Rodeo Sport', '$56918.35');
insert into car (make, model, price) values ('Lexus', 'LS', '$47253.20');
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', '$44139.60');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$77875.80');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$31513.41');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$57217.82');
insert into car (make, model, price) values ('Merkur', 'XR4Ti', '$48107.30');
insert into car (make, model, price) values ('GMC', 'Yukon', '$23368.98');
insert into car (make, model, price) values ('Mazda', 'CX-7', '$32112.77');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '$88912.56');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$74709.18');
insert into car (make, model, price) values ('Ford', 'Mustang', '$68216.05');
insert into car (make, model, price) values ('Toyota', 'MR2', '$45602.26');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$37729.00');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$24297.32');
insert into car (make, model, price) values ('Porsche', '911', '$35642.08');
insert into car (make, model, price) values ('BMW', 'M3', '$94258.05');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$67857.49');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$65831.41');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '$27751.06');
insert into car (make, model, price) values ('Geo', 'Tracker', '$48240.60');
insert into car (make, model, price) values ('Honda', 'CR-V', '$51195.92');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '$79628.26');
insert into car (make, model, price) values ('Cadillac', 'STS', '$23963.85');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '$47186.66');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$39829.69');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '$17157.17');
insert into car (make, model, price) values ('Chrysler', 'LeBaron', '$72659.71');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '$55596.11');
insert into car (make, model, price) values ('Nissan', 'Versa', '$52668.87');
insert into car (make, model, price) values ('Subaru', 'Impreza WRX', '$98688.27');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '$38337.23');
insert into car (make, model, price) values ('Chrysler', 'Sebring', '$98997.95');
insert into car (make, model, price) values ('Buick', 'LaCrosse', '$89791.57');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '$77253.54');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '$31709.32');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '$73459.37');
insert into car (make, model, price) values ('Land Rover', 'Freelander', '$99526.19');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$59411.14');
insert into car (make, model, price) values ('Toyota', 'Camry', '$88551.74');
insert into car (make, model, price) values ('Hyundai', 'Veracruz', '$86350.42');
insert into car (make, model, price) values ('Mercury', 'Sable', '$41144.31');
insert into car (make, model, price) values ('Honda', 'Civic', '$97317.39');
insert into car (make, model, price) values ('Subaru', 'Impreza', '$41913.23');
insert into car (make, model, price) values ('Plymouth', 'Breeze', '$82442.28');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$36284.20');
insert into car (make, model, price) values ('Buick', 'Regal', '$24419.38');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$16343.71');
insert into car (make, model, price) values ('BMW', '3 Series', '$76533.55');
insert into car (make, model, price) values ('Lincoln', 'MKX', '$44127.05');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$32708.76');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$18416.89');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$79031.08');
insert into car (make, model, price) values ('Dodge', 'Ram Van B250', '$42275.25');
insert into car (make, model, price) values ('GMC', 'Acadia', '$63377.17');
insert into car (make, model, price) values ('Toyota', '4Runner', '$45217.84');
insert into car (make, model, price) values ('Jensen', 'Interceptor', '$30726.62');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '$89355.97');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$68382.17');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '$89335.72');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$60612.10');
insert into car (make, model, price) values ('Mazda', '929', '$48273.02');
insert into car (make, model, price) values ('Volvo', 'V50', '$52179.51');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '$72538.66');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '$45949.33');
insert into car (make, model, price) values ('Ford', 'E350', '$96637.35');
insert into car (make, model, price) values ('Saturn', 'VUE', '$90574.89');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '$13249.76');
insert into car (make, model, price) values ('Aston Martin', 'Vanquish S', '$19962.91');
insert into car (make, model, price) values ('Isuzu', 'i-290', '$96840.07');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '$78186.21');
insert into car (make, model, price) values ('Dodge', 'D250', '$45689.77');
insert into car (make, model, price) values ('Honda', 'Civic', '$75836.50');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$87929.47');
insert into car (make, model, price) values ('Buick', 'Rainier', '$76744.98');
insert into car (make, model, price) values ('Eagle', 'Summit', '$52407.57');
insert into car (make, model, price) values ('BMW', '5 Series', '$63969.25');
insert into car (make, model, price) values ('Dodge', 'Viper', '$91745.26');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '$43963.27');
insert into car (make, model, price) values ('Saab', '9000', '$37066.98');
insert into car (make, model, price) values ('Audi', 'Q5', '$77527.49');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$12046.42');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '$29474.92');
insert into car (make, model, price) values ('BMW', 'M3', '$40857.33');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '$24539.10');
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', '$21926.99');
insert into car (make, model, price) values ('Volkswagen', 'Eos', '$46145.97');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$11284.96');
insert into car (make, model, price) values ('Mercury', 'Sable', '$35590.93');
insert into car (make, model, price) values ('Audi', 'S5', '$38675.84');
insert into car (make, model, price) values ('Audi', 'A4', '$21501.34');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '$94664.47');
insert into car (make, model, price) values ('Toyota', 'Corolla', '$84738.66');
insert into car (make, model, price) values ('BMW', '325', '$30233.79');
insert into car (make, model, price) values ('Hummer', 'H3T', '$69590.01');
insert into car (make, model, price) values ('Toyota', 'TundraMax', '$30737.14');
insert into car (make, model, price) values ('Lexus', 'LS', '$99989.58');
insert into car (make, model, price) values ('Chevrolet', 'S10', '$17259.83');
insert into car (make, model, price) values ('Lincoln', 'LS', '$24122.04');
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', '$11127.60');
insert into car (make, model, price) values ('Nissan', 'Xterra', '$61793.27');
insert into car (make, model, price) values ('GMC', 'Acadia', '$34856.36');
insert into car (make, model, price) values ('Volkswagen', 'CC', '$70959.38');
insert into car (make, model, price) values ('Eagle', 'Talon', '$70139.61');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '$22933.82');
insert into car (make, model, price) values ('Isuzu', 'Stylus', '$43025.04');
insert into car (make, model, price) values ('Ford', 'E-Series', '$17535.08');
insert into car (make, model, price) values ('Dodge', 'Avenger', '$88987.38');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$27775.86');
insert into car (make, model, price) values ('Ford', 'Ranger', '$28316.45');
insert into car (make, model, price) values ('Buick', 'Enclave', '$73583.07');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$98827.25');
insert into car (make, model, price) values ('Kia', 'Sorento', '$78108.25');
insert into car (make, model, price) values ('Toyota', 'Previa', '$71087.68');
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', '$42224.21');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '$65924.76');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '$83922.58');
insert into car (make, model, price) values ('Lexus', 'LS', '$87558.90');
insert into car (make, model, price) values ('Nissan', '300ZX', '$38750.13');
insert into car (make, model, price) values ('Subaru', 'Alcyone SVX', '$65411.30');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '$14193.47');
insert into car (make, model, price) values ('Subaru', 'Baja', '$54227.56');
insert into car (make, model, price) values ('Audi', '200', '$78507.10');
insert into car (make, model, price) values ('Ford', 'Mustang', '$59545.20');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '$30959.51');
insert into car (make, model, price) values ('Honda', 'Pilot', '$66696.37');
insert into car (make, model, price) values ('Saturn', 'Relay', '$16940.45');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$80868.86');
insert into car (make, model, price) values ('Audi', 'A6', '$93862.28');
insert into car (make, model, price) values ('Chevrolet', 'Corsica', '$83820.46');
insert into car (make, model, price) values ('Saab', '900', '$70719.69');
insert into car (make, model, price) values ('Mercury', 'Villager', '$50148.14');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '$43665.49');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '$83081.79');
insert into car (make, model, price) values ('Dodge', 'Viper RT/10', '$70774.58');
insert into car (make, model, price) values ('Saab', '9000', '$37470.10');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$46569.23');
insert into car (make, model, price) values ('Honda', 'Fit', '$66925.46');
insert into car (make, model, price) values ('Volvo', 'XC60', '$48077.79');
insert into car (make, model, price) values ('Lexus', 'GS', '$26648.25');
insert into car (make, model, price) values ('Buick', 'Somerset', '$27378.20');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '$54040.13');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '$77435.56');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '$37173.16');
insert into car (make, model, price) values ('Hummer', 'H1', '$10677.89');
insert into car (make, model, price) values ('Acura', 'Legend', '$10265.92');
insert into car (make, model, price) values ('BMW', '6 Series', '$18944.58');
insert into car (make, model, price) values ('Ford', 'Aspire', '$74491.65');
insert into car (make, model, price) values ('Saab', '9-2X', '$75709.37');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '$38593.76');
insert into car (make, model, price) values ('Nissan', 'Cube', '$70561.51');
insert into car (make, model, price) values ('Audi', '4000s Quattro', '$67377.79');
insert into car (make, model, price) values ('Oldsmobile', '88', '$51210.27');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '$31006.19');
insert into car (make, model, price) values ('Dodge', 'Stratus', '$32944.66');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$98422.39');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$31545.71');
insert into car (make, model, price) values ('Mazda', 'B2600', '$40540.09');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$99890.11');
insert into car (make, model, price) values ('Kia', 'Spectra', '$60860.63');
insert into car (make, model, price) values ('Saab', '9-5', '$60916.18');
insert into car (make, model, price) values ('Hummer', 'H2 SUV', '$95290.91');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$52410.41');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '$51059.06');
insert into car (make, model, price) values ('BMW', '530', '$87782.35');
insert into car (make, model, price) values ('Nissan', 'Murano', '$56060.57');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$60088.38');
insert into car (make, model, price) values ('Mazda', '323', '$67949.30');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '$82528.26');
insert into car (make, model, price) values ('Ford', 'E-350 Super Duty', '$43704.12');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$90628.35');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$20193.31');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '$64427.98');
insert into car (make, model, price) values ('Toyota', 'RAV4', '$10012.31');
insert into car (make, model, price) values ('Nissan', 'Quest', '$43450.32');
insert into car (make, model, price) values ('Subaru', 'Outback Sport', '$59123.28');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '$62202.04');
insert into car (make, model, price) values ('Buick', 'Riviera', '$51169.08');
insert into car (make, model, price) values ('BMW', 'Z4', '$53278.02');
insert into car (make, model, price) values ('Suzuki', 'Kizashi', '$20975.46');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$95635.59');
insert into car (make, model, price) values ('Chevrolet', 'Aveo', '$33702.06');
insert into car (make, model, price) values ('Honda', 'Insight', '$48655.25');
insert into car (make, model, price) values ('Nissan', '350Z Roadster', '$52281.41');
insert into car (make, model, price) values ('Bentley', 'Continental GTC', '$93563.13');
insert into car (make, model, price) values ('Lotus', 'Exige', '$82908.23');
insert into car (make, model, price) values ('Lexus', 'LS', '$76964.74');
insert into car (make, model, price) values ('Dodge', 'Viper RT/10', '$76889.45');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$11269.59');
insert into car (make, model, price) values ('Cadillac', 'Catera', '$14637.04');
insert into car (make, model, price) values ('Honda', 'Prelude', '$54787.93');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '$75447.04');
insert into car (make, model, price) values ('Dodge', 'Challenger', '$28003.68');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$87538.54');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$72432.54');
insert into car (make, model, price) values ('Cadillac', 'DTS', '$63235.57');
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', '$92057.28');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '$42603.82');
insert into car (make, model, price) values ('Saab', '9-5', '$28420.43');
insert into car (make, model, price) values ('Toyota', 'Highlander', '$65213.67');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$53180.72');
insert into car (make, model, price) values ('Eagle', 'Vision', '$53254.48');
insert into car (make, model, price) values ('Bentley', 'Arnage', '$30729.39');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$12138.68');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '$78759.04');
insert into car (make, model, price) values ('Hummer', 'H1', '$69593.95');
insert into car (make, model, price) values ('Porsche', '928', '$32267.95');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$75817.75');
insert into car (make, model, price) values ('Audi', 'Coupe Quattro', '$66566.72');
insert into car (make, model, price) values ('Buick', 'Terraza', '$31429.33');
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', '$99792.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$25601.02');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '$39351.98');
insert into car (make, model, price) values ('Jaguar', 'XK', '$95371.13');
insert into car (make, model, price) values ('Toyota', 'Prius', '$98211.23');
insert into car (make, model, price) values ('Nissan', 'Frontier', '$40144.39');
insert into car (make, model, price) values ('Dodge', 'Durango', '$81600.74');
insert into car (make, model, price) values ('Ford', 'Transit Connect', '$68627.14');
insert into car (make, model, price) values ('Citroën', 'CX', '$97152.17');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$72356.48');
insert into car (make, model, price) values ('Toyota', 'Matrix', '$81523.07');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '$91536.68');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '$87962.91');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '$93348.13');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$84117.48');
insert into car (make, model, price) values ('Toyota', 'Sienna', '$20399.55');
insert into car (make, model, price) values ('Volkswagen', 'Beetle', '$55937.65');
insert into car (make, model, price) values ('Nissan', 'Quest', '$22667.73');
insert into car (make, model, price) values ('Toyota', 'Paseo', '$80170.63');
insert into car (make, model, price) values ('Audi', 'Coupe GT', '$90907.28');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '$24393.46');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$92923.88');
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', '$63883.12');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$36754.92');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '$10939.16');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '$40599.08');
insert into car (make, model, price) values ('Mazda', 'B2600', '$90035.67');
insert into car (make, model, price) values ('Volkswagen', 'Phaeton', '$28665.23');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$31588.46');
insert into car (make, model, price) values ('Audi', 'S5', '$74645.03');
insert into car (make, model, price) values ('BMW', '7 Series', '$24942.73');
insert into car (make, model, price) values ('Acura', 'CL', '$81357.74');
insert into car (make, model, price) values ('Buick', 'Riviera', '$64732.22');
insert into car (make, model, price) values ('Suzuki', 'Daewoo Magnus', '$14952.77');
insert into car (make, model, price) values ('Mazda', '626', '$26619.76');
insert into car (make, model, price) values ('Ford', 'Courier', '$77116.37');
insert into car (make, model, price) values ('Smart', 'Fortwo', '$23203.24');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$56478.68');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '$60170.19');
insert into car (make, model, price) values ('Audi', 'A5', '$24843.69');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '$24985.36');
insert into car (make, model, price) values ('Acura', 'Integra', '$60814.48');
insert into car (make, model, price) values ('Scion', 'xD', '$77571.88');
insert into car (make, model, price) values ('Toyota', 'T100', '$39652.89');
insert into car (make, model, price) values ('BMW', 'X5', '$75255.80');
insert into car (make, model, price) values ('Nissan', 'Altima', '$68914.00');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '$50769.63');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '$28551.79');
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', '$47782.93');
insert into car (make, model, price) values ('BMW', '600', '$11277.87');
insert into car (make, model, price) values ('GMC', 'Safari', '$13456.95');
insert into car (make, model, price) values ('Honda', 'Civic', '$28876.97');
insert into car (make, model, price) values ('Toyota', 'Tundra', '$95416.16');
insert into car (make, model, price) values ('Lexus', 'GS', '$55183.42');
insert into car (make, model, price) values ('Mazda', 'Familia', '$46196.76');
insert into car (make, model, price) values ('Lexus', 'IS-F', '$52597.12');
insert into car (make, model, price) values ('Nissan', 'GT-R', '$17915.69');
insert into car (make, model, price) values ('Cadillac', 'CTS', '$43521.23');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$62960.04');
insert into car (make, model, price) values ('Ford', 'Transit Connect', '$98456.55');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '$72095.18');
insert into car (make, model, price) values ('Subaru', 'Outback', '$89929.43');
insert into car (make, model, price) values ('Lexus', 'SC', '$38353.07');
insert into car (make, model, price) values ('Suzuki', 'SJ', '$56627.90');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '$21641.65');
insert into car (make, model, price) values ('Mazda', 'Navajo', '$13074.50');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$74738.70');
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', '$34697.96');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '$77720.06');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '$99817.08');
insert into car (make, model, price) values ('Volkswagen', 'Type 2', '$96909.23');
insert into car (make, model, price) values ('Infiniti', 'QX', '$42528.35');
insert into car (make, model, price) values ('Saab', '9-5', '$90825.31');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '$89296.26');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$12958.60');
insert into car (make, model, price) values ('Mercury', 'Mystique', '$41888.07');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '$19562.35');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$15821.44');
insert into car (make, model, price) values ('Saab', '9-5', '$24769.13');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$53240.12');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '$69080.97');
insert into car (make, model, price) values ('Ford', 'E250', '$11204.58');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$15847.58');
insert into car (make, model, price) values ('Porsche', '928', '$45182.00');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '$27265.69');
insert into car (make, model, price) values ('Chevrolet', 'Corsica', '$50475.71');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '$78804.57');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$79747.96');
insert into car (make, model, price) values ('Ford', 'Fiesta', '$64828.09');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '$98312.20');
insert into car (make, model, price) values ('Suzuki', 'SJ', '$34924.20');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '$88353.56');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '$47835.43');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '$50839.50');
insert into car (make, model, price) values ('Lotus', 'Esprit', '$22727.42');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '$67582.73');
insert into car (make, model, price) values ('Honda', 'Insight', '$62325.67');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$13374.89');
insert into car (make, model, price) values ('Cadillac', 'XLR', '$14785.56');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$90836.71');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter', '$24586.06');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS AMG', '$66158.24');
insert into car (make, model, price) values ('Subaru', 'SVX', '$94935.46');
insert into car (make, model, price) values ('Nissan', 'Armada', '$90964.39');
insert into car (make, model, price) values ('Alfa Romeo', '164', '$64297.44');
insert into car (make, model, price) values ('Kia', 'Carens', '$57698.52');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$35450.97');
insert into car (make, model, price) values ('Lexus', 'IS', '$93795.62');
insert into car (make, model, price) values ('Acura', 'TSX', '$13489.49');
insert into car (make, model, price) values ('Nissan', 'Altima', '$88259.12');
insert into car (make, model, price) values ('Hyundai', 'Azera', '$12820.70');
insert into car (make, model, price) values ('Lotus', 'Elise', '$26310.40');
insert into car (make, model, price) values ('Toyota', 'Yaris', '$33581.56');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '$51774.27');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$35590.35');
insert into car (make, model, price) values ('Nissan', 'Murano', '$96136.18');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '$14411.14');
insert into car (make, model, price) values ('BMW', '8 Series', '$84994.71');
insert into car (make, model, price) values ('Ford', 'Mustang', '$64466.64');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '$59623.62');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '$13044.28');
insert into car (make, model, price) values ('Infiniti', 'Q', '$17245.85');
insert into car (make, model, price) values ('Saturn', 'VUE', '$22477.40');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$13345.26');
insert into car (make, model, price) values ('Infiniti', 'FX', '$40245.31');
insert into car (make, model, price) values ('Mazda', 'MX-5', '$46136.62');
insert into car (make, model, price) values ('Eagle', 'Vision', '$81218.17');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '$85847.78');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '$14853.97');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '$58380.64');
insert into car (make, model, price) values ('Mercury', 'Milan', '$47590.84');
insert into car (make, model, price) values ('Toyota', 'Solara', '$88641.45');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$52008.93');
insert into car (make, model, price) values ('Nissan', 'Maxima', '$90792.12');
insert into car (make, model, price) values ('Honda', 'Accord', '$96229.59');
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', '$31031.03');
insert into car (make, model, price) values ('Austin', 'Mini', '$95451.42');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '$52570.54');
insert into car (make, model, price) values ('Audi', 'TT', '$29445.17');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '$73902.01');
insert into car (make, model, price) values ('Audi', 'RS 6', '$68659.71');
insert into car (make, model, price) values ('Pontiac', 'Daewoo Kalos', '$72678.22');
insert into car (make, model, price) values ('Ford', 'Escort', '$84978.67');
insert into car (make, model, price) values ('Panoz', 'Esperante', '$67932.89');
insert into car (make, model, price) values ('Lexus', 'LX', '$89724.30');
insert into car (make, model, price) values ('GMC', 'Yukon', '$59447.07');
insert into car (make, model, price) values ('Mazda', '929', '$11004.94');
insert into car (make, model, price) values ('Toyota', 'Tundra', '$79440.91');
insert into car (make, model, price) values ('Buick', 'Skylark', '$29429.47');
insert into car (make, model, price) values ('Toyota', 'Prius', '$42615.40');
insert into car (make, model, price) values ('Chrysler', 'Crossfire', '$94283.66');
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', '$33163.26');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$92767.86');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '$63410.20');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '$67949.10');
insert into car (make, model, price) values ('Volvo', 'S60', '$33739.06');
insert into car (make, model, price) values ('Ford', 'Ranger', '$87999.71');
insert into car (make, model, price) values ('Mercury', 'Lynx', '$41054.85');
insert into car (make, model, price) values ('Infiniti', 'QX56', '$28446.77');
insert into car (make, model, price) values ('Eagle', 'Summit', '$91446.58');
insert into car (make, model, price) values ('Porsche', '928', '$13939.22');
insert into car (make, model, price) values ('Ford', 'Bronco', '$46842.15');
insert into car (make, model, price) values ('Saab', '9-5', '$71849.90');
insert into car (make, model, price) values ('Ford', 'F250', '$90182.36');
insert into car (make, model, price) values ('Toyota', 'Camry', '$50583.42');
insert into car (make, model, price) values ('Acura', 'RL', '$40449.15');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$88463.93');
insert into car (make, model, price) values ('Toyota', 'Camry', '$37151.35');
insert into car (make, model, price) values ('Honda', 'Civic', '$65256.33');
insert into car (make, model, price) values ('Dodge', 'Ram Van B350', '$83868.31');
insert into car (make, model, price) values ('Jaguar', 'XJ', '$45045.17');
insert into car (make, model, price) values ('Mazda', 'MX-3', '$12998.28');
insert into car (make, model, price) values ('Acura', 'RDX', '$78907.73');
insert into car (make, model, price) values ('Mazda', 'Mazda3', '$95417.69');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '$28857.00');
insert into car (make, model, price) values ('BMW', 'Z4 M', '$74878.58');
insert into car (make, model, price) values ('Ford', 'E250', '$71650.02');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '$31990.44');
insert into car (make, model, price) values ('Lincoln', 'MKX', '$92886.45');
insert into car (make, model, price) values ('GMC', 'Sierra', '$42758.74');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$27329.53');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$12827.01');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '$35098.97');
insert into car (make, model, price) values ('Porsche', '968', '$47949.80');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '$11691.04');
insert into car (make, model, price) values ('Lexus', 'IS-F', '$66532.02');
insert into car (make, model, price) values ('Pontiac', 'Safari', '$75164.96');
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', '$34824.77');
insert into car (make, model, price) values ('Saab', '900', '$87729.36');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G10', '$44148.03');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '$20034.24');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$65683.97');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$72608.98');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '$12522.72');
insert into car (make, model, price) values ('Toyota', 'Corolla', '$21956.98');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$26390.37');
insert into car (make, model, price) values ('Pontiac', '1000', '$69808.45');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$96170.84');
insert into car (make, model, price) values ('Buick', 'Reatta', '$79217.57');
insert into car (make, model, price) values ('Ford', 'F250', '$84491.54');
insert into car (make, model, price) values ('Mazda', 'MX-6', '$93571.17');
insert into car (make, model, price) values ('Suzuki', 'SJ', '$33324.10');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '$61256.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$97346.56');
insert into car (make, model, price) values ('Chevrolet', 'HHR', '$84261.88');
insert into car (make, model, price) values ('Ford', 'GT500', '$52917.23');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$82175.82');
insert into car (make, model, price) values ('Chevrolet', 'SSR', '$21200.78');
insert into car (make, model, price) values ('Volvo', 'S60', '$24469.29');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '$36813.98');
insert into car (make, model, price) values ('GMC', 'Rally Wagon G3500', '$13092.29');
insert into car (make, model, price) values ('Toyota', '4Runner', '$22412.41');
insert into car (make, model, price) values ('BMW', '3 Series', '$62090.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$72579.87');
insert into car (make, model, price) values ('Ford', 'Contour', '$91838.75');
insert into car (make, model, price) values ('Toyota', 'T100', '$92677.32');
insert into car (make, model, price) values ('GMC', 'Savana', '$77414.91');
insert into car (make, model, price) values ('Ford', 'F150', '$25554.14');
insert into car (make, model, price) values ('Isuzu', 'Impulse', '$66648.42');
insert into car (make, model, price) values ('Maserati', 'Biturbo', '$20217.11');
insert into car (make, model, price) values ('Ford', 'Ranger', '$26024.72');
insert into car (make, model, price) values ('Toyota', 'Solara', '$19628.74');
insert into car (make, model, price) values ('BMW', '3 Series', '$20655.26');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$34114.21');
insert into car (make, model, price) values ('Kia', 'Sorento', '$66979.09');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$46204.34');
insert into car (make, model, price) values ('Toyota', 'Highlander', '$61569.56');
insert into car (make, model, price) values ('Hummer', 'H1', '$81094.80');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '$75604.41');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$88920.69');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '$17892.05');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '$82736.74');
insert into car (make, model, price) values ('Lexus', 'LX', '$69400.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$89334.71');
insert into car (make, model, price) values ('BMW', 'Z4', '$84534.04');
insert into car (make, model, price) values ('Mazda', '929', '$35578.12');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$38944.85');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '$83372.66');
insert into car (make, model, price) values ('Ford', 'Ranger', '$73948.08');
insert into car (make, model, price) values ('Audi', '200', '$93161.57');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '$39084.75');
insert into car (make, model, price) values ('Buick', 'Hearse', '$50053.74');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '$18608.25');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '$98640.46');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '$91936.11');
insert into car (make, model, price) values ('Saturn', 'Aura', '$34116.05');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$34552.13');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '$80113.08');
insert into car (make, model, price) values ('Toyota', 'Celica', '$58117.61');
insert into car (make, model, price) values ('Toyota', 'RAV4', '$74773.20');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$63474.57');
insert into car (make, model, price) values ('GMC', 'Sonoma', '$34136.21');
insert into car (make, model, price) values ('Dodge', 'Caravan', '$74095.21');
insert into car (make, model, price) values ('Dodge', 'Stratus', '$46695.35');
insert into car (make, model, price) values ('Nissan', '200SX', '$13178.76');
insert into car (make, model, price) values ('Toyota', 'Prius', '$56103.91');
insert into car (make, model, price) values ('Peugeot', '207', '$96084.13');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$51211.01');
insert into car (make, model, price) values ('Ford', 'E-Series', '$81350.43');
insert into car (make, model, price) values ('Kia', 'Rio', '$34288.72');
insert into car (make, model, price) values ('Buick', 'LeSabre', '$60882.19');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '$55045.93');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '$15825.33');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '$63472.88');
insert into car (make, model, price) values ('Buick', 'Roadmaster', '$44614.88');
insert into car (make, model, price) values ('Nissan', 'Sentra', '$92576.73');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$44370.26');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$31429.28');
insert into car (make, model, price) values ('Mercury', 'Sable', '$63826.98');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '$72915.66');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '$41298.12');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$60241.85');
insert into car (make, model, price) values ('Hyundai', 'Accent', '$42382.88');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$60558.06');
insert into car (make, model, price) values ('Jaguar', 'XF', '$46922.66');
insert into car (make, model, price) values ('Ford', 'Galaxie', '$63239.06');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '$19565.72');
insert into car (make, model, price) values ('Volkswagen', 'Eos', '$65459.12');
insert into car (make, model, price) values ('Audi', 'A8', '$13209.13');
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', '$74396.82');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '$96889.01');
insert into car (make, model, price) values ('Nissan', 'JUKE', '$52772.06');
insert into car (make, model, price) values ('BMW', '745', '$93635.67');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '$21927.25');
insert into car (make, model, price) values ('Subaru', 'Legacy', '$59919.50');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '$68046.66');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '$79502.59');
insert into car (make, model, price) values ('Saturn', 'VUE', '$87901.62');
insert into car (make, model, price) values ('Lotus', 'Exige', '$85860.88');
insert into car (make, model, price) values ('Acura', 'Integra', '$26592.24');
insert into car (make, model, price) values ('Lexus', 'LS', '$78590.35');
insert into car (make, model, price) values ('Acura', 'CL', '$34395.13');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '$31248.44');
insert into car (make, model, price) values ('Audi', 'Q7', '$52490.47');
insert into car (make, model, price) values ('Dodge', 'Viper', '$50740.12');
insert into car (make, model, price) values ('BMW', 'Z8', '$52623.97');
insert into car (make, model, price) values ('Toyota', 'Avalon', '$68998.43');
insert into car (make, model, price) values ('Nissan', 'Altima', '$55550.77');
insert into car (make, model, price) values ('Eagle', 'Summit', '$92773.28');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '$60932.44');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '$22061.46');
insert into car (make, model, price) values ('Honda', 'CR-V', '$11739.35');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$80111.19');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '$53827.38');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '$30650.77');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '$81989.73');
insert into car (make, model, price) values ('Pontiac', 'Montana SV6', '$98788.15');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '$13481.47');
insert into car (make, model, price) values ('Dodge', 'Charger', '$92295.95');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$28914.92');
insert into car (make, model, price) values ('Ford', 'Explorer', '$42618.46');
insert into car (make, model, price) values ('Cadillac', 'XLR', '$17447.20');
insert into car (make, model, price) values ('Kia', 'Sorento', '$99504.88');
insert into car (make, model, price) values ('Mazda', 'Protege', '$69530.63');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$69102.22');
insert into car (make, model, price) values ('Ford', 'F450', '$68790.23');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '$13121.34');
insert into car (make, model, price) values ('MINI', 'Countryman', '$97312.73');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '$70503.51');
insert into car (make, model, price) values ('Mazda', 'Mazda2', '$34464.91');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '$42395.68');
insert into car (make, model, price) values ('Suzuki', 'SJ', '$79883.36');
insert into car (make, model, price) values ('GMC', 'Rally Wagon G2500', '$88405.25');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '$50045.73');
insert into car (make, model, price) values ('Ford', 'F450', '$24459.18');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '$10856.77');
insert into car (make, model, price) values ('Dodge', 'D350', '$54834.11');
insert into car (make, model, price) values ('Lexus', 'ES', '$80128.15');
insert into car (make, model, price) values ('Ford', 'F350', '$12554.89');
insert into car (make, model, price) values ('Saturn', 'S-Series', '$51264.38');
insert into car (make, model, price) values ('Mercury', 'Tracer', '$29425.69');
insert into car (make, model, price) values ('GMC', 'Savana', '$83016.09');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '$74422.49');
insert into car (make, model, price) values ('Lexus', 'GS', '$13989.52');
insert into car (make, model, price) values ('BMW', 'X3', '$76775.25');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '$52740.36');
insert into car (make, model, price) values ('Plymouth', 'Colt Vista', '$71823.39');
insert into car (make, model, price) values ('Jaguar', 'XJ', '$39205.13');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$94494.28');
insert into car (make, model, price) values ('Pontiac', 'Montana', '$23816.76');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '$41352.79');
insert into car (make, model, price) values ('Hyundai', 'Genesis', '$52840.23');
insert into car (make, model, price) values ('Honda', 'Prelude', '$67790.03');
insert into car (make, model, price) values ('Chevrolet', 'Tracker', '$48979.38');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '$75408.38');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '$92746.42');
insert into car (make, model, price) values ('Lexus', 'GX', '$24508.48');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '$25323.16');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '$95604.21');
insert into car (make, model, price) values ('Infiniti', 'G25', '$33745.32');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '$48342.09');
insert into car (make, model, price) values ('Acura', 'TSX', '$50159.07');
insert into car (make, model, price) values ('Ford', 'E-Series', '$51288.35');
insert into car (make, model, price) values ('Audi', 'S8', '$97220.41');
insert into car (make, model, price) values ('Audi', 'Q5', '$84698.41');
insert into car (make, model, price) values ('Ford', 'E-Series', '$43480.09');
insert into car (make, model, price) values ('Dodge', 'Spirit', '$51057.76');
insert into car (make, model, price) values ('Chevrolet', 'Prizm', '$83243.80');
insert into car (make, model, price) values ('BMW', 'M5', '$61705.85');
insert into car (make, model, price) values ('Honda', 'Odyssey', '$13572.31');
insert into car (make, model, price) values ('Audi', 'S4', '$51028.84');
insert into car (make, model, price) values ('Volvo', 'C30', '$77413.29');
insert into car (make, model, price) values ('Scion', 'FR-S', '$95475.37');
insert into car (make, model, price) values ('Daewoo', 'Nubira', '$97544.36');
insert into car (make, model, price) values ('Subaru', 'Brat', '$58675.58');
insert into car (make, model, price) values ('Dodge', 'Charger', '$28936.07');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$32239.30');
insert into car (make, model, price) values ('Buick', 'Enclave', '$62191.16');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '$12201.98');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '$71673.17');
insert into car (make, model, price) values ('GMC', 'Vandura 1500', '$72340.41');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$77199.36');
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', '$61729.24');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '$77234.47');
insert into car (make, model, price) values ('Honda', 'Accord', '$54226.22');
insert into car (make, model, price) values ('Lexus', 'SC', '$99246.18');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '$90530.55');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '$85875.67');
insert into car (make, model, price) values ('Ford', 'Edge', '$53677.69');
insert into car (make, model, price) values ('Infiniti', 'QX', '$18266.37');
insert into car (make, model, price) values ('Mazda', 'MX-6', '$54449.66');
insert into car (make, model, price) values ('Mitsubishi', 'Sigma', '$35565.33');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$88661.48');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '$23652.50');
insert into car (make, model, price) values ('Audi', 'R8', '$21315.36');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$63861.53');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', '$76512.31');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '$69445.51');
insert into car (make, model, price) values ('Lexus', 'GS', '$16067.69');
insert into car (make, model, price) values ('Mercury', 'Mariner', '$84374.59');
insert into car (make, model, price) values ('Saturn', 'Aura', '$66305.61');
insert into car (make, model, price) values ('Ford', 'Contour', '$91807.86');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '$28969.89');
insert into car (make, model, price) values ('Mazda', 'Familia', '$61898.60');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$79346.94');
insert into car (make, model, price) values ('BMW', 'Z4', '$98199.69');
insert into car (make, model, price) values ('Honda', 'S2000', '$99518.29');
insert into car (make, model, price) values ('Infiniti', 'G35', '$33129.71');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '$17359.33');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '$35149.13');
insert into car (make, model, price) values ('Ford', 'Escort', '$49830.93');
insert into car (make, model, price) values ('Lexus', 'GS', '$67191.38');
insert into car (make, model, price) values ('Mercury', 'Cougar', '$13430.47');
insert into car (make, model, price) values ('Toyota', 'Camry', '$90928.13');
insert into car (make, model, price) values ('Suzuki', 'SX4', '$96508.83');
insert into car (make, model, price) values ('Mercury', 'Sable', '$68931.66');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '$39175.92');
insert into car (make, model, price) values ('Infiniti', 'EX', '$24395.91');
insert into car (make, model, price) values ('Buick', 'LaCrosse', '$41317.11');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$74103.26');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$97892.20');
insert into car (make, model, price) values ('Ford', 'Mustang', '$92648.28');
insert into car (make, model, price) values ('Audi', 'S5', '$59236.37');
insert into car (make, model, price) values ('Ford', 'F150', '$86785.20');
insert into car (make, model, price) values ('Audi', 'S8', '$44576.92');
insert into car (make, model, price) values ('Lexus', 'SC', '$94115.89');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '$74380.41');
insert into car (make, model, price) values ('GMC', 'Safari', '$55404.35');
insert into car (make, model, price) values ('Buick', 'Regal', '$99459.64');
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', '$96851.63');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '$42741.38');
insert into car (make, model, price) values ('Suzuki', 'Swift', '$77050.54');
insert into car (make, model, price) values ('Mazda', 'Millenia', '$35514.83');
insert into car (make, model, price) values ('Ford', 'Tempo', '$97206.65');
insert into car (make, model, price) values ('Volvo', '960', '$83642.82');
insert into car (make, model, price) values ('Mazda', '929', '$81528.91');
insert into car (make, model, price) values ('Toyota', 'Celica', '$28844.70');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '$78504.99');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '$29334.11');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '$99934.92');
insert into car (make, model, price) values ('Ford', 'Explorer', '$21320.08');
insert into car (make, model, price) values ('Dodge', 'Magnum', '$99301.49');
insert into car (make, model, price) values ('Ram', '3500', '$23458.13');
insert into car (make, model, price) values ('Audi', 'Quattro', '$49420.38');
insert into car (make, model, price) values ('BMW', 'Z3', '$91397.37');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '$12417.53');
insert into car (make, model, price) values ('BMW', 'X5', '$32054.94');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '$30181.14');
insert into car (make, model, price) values ('Pontiac', '6000', '$17703.07');
insert into car (make, model, price) values ('Lincoln', 'Continental', '$65361.00');
insert into car (make, model, price) values ('Jeep', 'Liberty', '$17010.97');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '$47377.46');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '$77269.80');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '$70910.21');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '$54392.89');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$39752.91');
insert into car (make, model, price) values ('BMW', '330', '$29140.42');
insert into car (make, model, price) values ('Lincoln', 'Aviator', '$86841.60');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '$81573.38');
insert into car (make, model, price) values ('Mazda', 'B-Series', '$27057.19');
insert into car (make, model, price) values ('Chevrolet', 'Classic', '$23388.47');
insert into car (make, model, price) values ('Toyota', 'Yaris', '$75406.57');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '$34534.49');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '$64085.80');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '$67063.21');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '$39953.23');
insert into car (make, model, price) values ('Maybach', '62', '$31057.76');
insert into car (make, model, price) values ('Dodge', 'Dakota', '$79583.37');
insert into car (make, model, price) values ('Audi', 'TT', '$73574.78');
insert into car (make, model, price) values ('Ford', 'Econoline E150', '$77818.77');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '$72100.12');
insert into car (make, model, price) values ('Ford', 'Escort', '$11414.82');
insert into car (make, model, price) values ('Dodge', 'Viper', '$41954.41');
insert into car (make, model, price) values ('Ford', 'E150', '$89226.46');
insert into car (make, model, price) values ('Ford', 'F150', '$51405.30');
insert into car (make, model, price) values ('Dodge', 'Daytona', '$72957.72');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '$82969.28');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '$96693.57');
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', '$32057.50');
insert into car (make, model, price) values ('Lexus', 'GS', '$23723.29');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '$15983.67');
insert into car (make, model, price) values ('MG', 'MGB', '$64288.94');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '$18360.42');
insert into car (make, model, price) values ('Ford', 'Probe', '$50403.63');
insert into car (make, model, price) values ('BMW', '5 Series', '$88534.56');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '$39100.54');
insert into car (make, model, price) values ('Ford', 'Windstar', '$74455.87');
insert into car (make, model, price) values ('Eagle', 'Summit', '$74238.69');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '$67954.94');
