# Generated by Django 4.2.11 on 2024-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='dial_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
