# Generated by Django 4.2.11 on 2024-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_category_value_category_dial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
