# Generated by Django 4.2.11 on 2024-04-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='value',
            new_name='name',
        ),
    ]
