# Generated by Django 4.2.11 on 2024-04-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_value_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='options',
            name='field',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
